/*
 * embed_html.cpp — Converts index.html → html_data.cpp (C char array)
 * Usage: ./embed_html src/index.html > build/html_data.cpp
 */
#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <iomanip>

int main(int argc, char* argv[]) {
    if (argc < 2) {
        std::cerr << "Usage: " << argv[0] << " <html_file>\n";
        return 1;
    }

    std::ifstream f(argv[1], std::ios::binary);
    if (!f) {
        std::cerr << "Cannot open: " << argv[1] << "\n";
        return 1;
    }

    std::vector<unsigned char> data(
        (std::istreambuf_iterator<char>(f)),
        std::istreambuf_iterator<char>()
    );

    std::cout << "/* Auto-generated by embed_html — do not edit */\n";
    std::cout << "#include <stddef.h>\n\n";
    std::cout << "extern \"C\" {\n\n";
    std::cout << "extern const unsigned char g_html[] = {\n  ";

    for (size_t i = 0; i < data.size(); ++i) {
        std::cout << "0x" << std::hex << std::setw(2) << std::setfill('0')
                  << static_cast<int>(data[i]) << ",";
        if ((i + 1) % 16 == 0) std::cout << "\n  ";
    }

    std::cout << "0x00\n};\n\n";
    std::cout << std::dec;
    std::cout << "extern const size_t g_html_len = " << data.size() << ";\n\n";
    std::cout << "} // extern \"C\"\n";

    return 0;
}
