/*
 * main.cpp — pgwebapp C++ PostgreSQL Web Studio
 *
 * Architecture:
 *   HttpServer  → routes HTTP requests
 *   Database    → wraps libpq (RAII, thread-safe)
 *   Json        → builds JSON responses
 *   Utils       → URL/form parsing
 *
 * Compile:  g++ -std=c++17 -O2 -Wall -o pgwebapp main.cpp -lpq -lpthread
 * Run:      ./pgwebapp [port]   (default: 8080)
 */

#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <csignal>
#include <cstdlib>
#include <stdexcept>

#include "HttpServer.hpp"
#include "Database.hpp"
#include "Json.hpp"
#include "Utils.hpp"

/* ── Embedded HTML (generated by embed_html tool) ─────────── */
extern "C" {
    extern const unsigned char g_html[];
    extern const size_t g_html_len;
}

/* ── Global database instance (thread-safe internally) ────── */
static Database g_db;

/* ── Signal handling ───────────────────────────────────────── */
static HttpServer* g_server_ptr = nullptr;

static void sig_handler(int) {
    std::cout << "\n[pgwebapp] Shutting down...\n";
    if (g_server_ptr) g_server_ptr->stop();
}

/* ════════════════════════════════════════════════════════════
   Route Handlers
   ════════════════════════════════════════════════════════════ */

/* GET / — serve the embedded web UI */
HttpResponse handle_index(const HttpRequest&) {
    return HttpResponse::html(std::string(reinterpret_cast<const char*>(g_html), g_html_len));
}

/* POST /api/connect */
HttpResponse handle_connect(const HttpRequest& req) {
    auto f = Utils::parse_form(req.body);

    ConnParams p;
    p.host             = Utils::field(f, "host",             "localhost");
    p.port             = Utils::field(f, "port",             "5432");
    p.dbname           = Utils::field(f, "dbname");
    p.user             = Utils::field(f, "user");
    p.password         = Utils::field(f, "password");
    p.sslmode          = Utils::field(f, "sslmode",          "prefer");
    p.connect_timeout  = Utils::field(f, "connect_timeout",  "10");
    p.application_name = Utils::field(f, "application_name", "pgwebapp_cpp");

    try {
        auto info = g_db.connect(p);
        auto body = Json::Object()
            .str("status",         "ok")
            .str("message",        "Connected successfully")
            .str("server_version", info.server_version)
            .str("database",       info.database)
            .str("user",           info.user)
            .str("host",           info.host)
            .str("port",           info.port)
            .build();
        return HttpResponse::json(200, body);

    } catch (const std::exception& e) {
        auto body = Json::Object()
            .str("status",  "error")
            .str("message", e.what())
            .build();
        return HttpResponse::json(200, body);
    }
}

/* POST /api/disconnect */
HttpResponse handle_disconnect(const HttpRequest&) {
    g_db.disconnect();
    auto body = Json::Object()
        .str("status",  "ok")
        .str("message", "Disconnected")
        .build();
    return HttpResponse::json(200, body);
}

/* GET /api/status */
HttpResponse handle_status(const HttpRequest&) {
    if (!g_db.is_connected()) {
        auto body = Json::Object()
            .boolean("connected", false)
            .build();
        return HttpResponse::json(200, body);
    }
    auto info = g_db.current_info();
    auto body = Json::Object()
        .boolean("connected", true)
        .str("database", info.database)
        .str("user",     info.user)
        .str("host",     info.host)
        .build();
    return HttpResponse::json(200, body);
}

/* POST /api/query */
HttpResponse handle_query(const HttpRequest& req) {
    auto f     = Utils::parse_form(req.body);
    auto sql   = Utils::field(f, "query");

    if (sql.empty()) {
        auto body = Json::Object()
            .str("status",  "error")
            .str("message", "Empty query")
            .build();
        return HttpResponse::json(200, body);
    }

    auto result = g_db.execute(sql);
    std::string body;

    switch (result.type) {

    case QueryResult::Type::SELECT: {
        /* Build columns array */
        Json::Array cols_json;
        for (auto& col : result.columns) {
            auto obj = Json::Object()
                .str("name", col.name)
                .set("type", Json::number(col.oid))
                .build();
            cols_json.push(obj);
        }

        /* Build data array (array of arrays) */
        Json::Array data_json;
        for (size_t r = 0; r < result.rows.size(); ++r) {
            Json::Array row_json;
            for (size_t c = 0; c < result.rows[r].size(); ++c) {
                if (result.null_flags[r][c]) {
                    row_json.push(Json::null_val());
                } else {
                    row_json.push(Json::str(result.rows[r][c]));
                }
            }
            data_json.push(row_json.build());
        }

        body = Json::Object()
            .str("status",     "ok")
            .str("type",       "SELECT")
            .set("rows",       Json::number(static_cast<int>(result.rows.size())))
            .set("cols",       Json::number(static_cast<int>(result.columns.size())))
            .set("elapsed_ms", Json::number(result.elapsed_ms))
            .set("columns",    cols_json.build())
            .set("data",       data_json.build())
            .build();
        break;
    }

    case QueryResult::Type::COMMAND: {
        body = Json::Object()
            .str("status",        "ok")
            .str("type",          "COMMAND")
            .str("rows_affected", result.rows_affected)
            .str("command",       result.command_tag)
            .set("elapsed_ms",    Json::number(result.elapsed_ms))
            .build();
        break;
    }

    case QueryResult::Type::ERROR:
    default: {
        body = Json::Object()
            .str("status",     "error")
            .str("message",    result.error_message)
            .set("elapsed_ms", Json::number(result.elapsed_ms))
            .build();
        break;
    }
    }

    return HttpResponse::json(200, body);
}

/* ════════════════════════════════════════════════════════════
   main()
   ════════════════════════════════════════════════════════════ */
int main(int argc, char* argv[]) {
    int port = 8080;
    if (argc > 1) {
        port = std::atoi(argv[1]);
        if (port <= 0 || port > 65535) {
            std::cerr << "Invalid port: " << argv[1] << "\n";
            return 1;
        }
    }

    /* Ignore broken pipe signals */
    signal(SIGPIPE, SIG_IGN);

    HttpServer server(port);
    g_server_ptr = &server;

    signal(SIGINT,  sig_handler);
    signal(SIGTERM, sig_handler);

    /* Register all routes */
    server.route("GET",  "/",                handle_index);
    server.route("GET",  "/index.html",      handle_index);
    server.route("POST", "/api/connect",     handle_connect);
    server.route("POST", "/api/disconnect",  handle_disconnect);
    server.route("GET",  "/api/status",      handle_status);
    server.route("POST", "/api/query",       handle_query);

    std::cout << "\n"
              << "  ╔══════════════════════════════════════════╗\n"
              << "  ║    pgwebapp C++ — PostgreSQL Studio      ║\n"
              << "  ╠══════════════════════════════════════════╣\n"
              << "  ║  Server : http://localhost:" << port
              << std::string(13 - std::to_string(port).size(), ' ') << "║\n"
              << "  ║  Backend: C++17 + libpq                  ║\n"
              << "  ║  Press Ctrl+C to stop                    ║\n"
              << "  ╚══════════════════════════════════════════╝\n\n";

    try {
        server.listen_and_serve();
    } catch (const std::exception& e) {
        std::cerr << "[error] " << e.what() << "\n";
        return 1;
    }

    g_db.disconnect();
    return 0;
}
